"""
Morning report routes.

GET  /report                     → SSE stream of the morning briefing
GET  /report/status              → which integrations are configured
GET  /report/latest              → last cached report (generated by scheduler)
GET  /report/schedule            → scheduling settings {enabled, time}
PUT  /report/schedule            → update scheduling settings
GET  /report/calendar/auth       → returns Google OAuth URL
POST /report/calendar/callback   → exchange auth code, store token
DELETE /report/calendar          → disconnect Google Calendar
GET  /report/calendar/events     → today's calendar events
"""

import json
from typing import AsyncIterator

from fastapi import APIRouter, Depends
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from sqlalchemy.orm import Session

from api.dependencies import get_db, get_ollama
from core.ollama_client import OllamaClient
from core.integrations.report_service import morning_report_service
from core.integrations.calendar_client import calendar_client
from core.integrations.weather import weather_client
from core.integrations.news import news_client
from core.encryption import encrypt_field, decrypt_field
from core.config import settings as app_settings
from db.crud import profile as profile_crud
from db.crud import settings as settings_crud
from db.models import GoogleCalendarToken

router = APIRouter()


def _sse(data: dict) -> str:
    return f"data: {json.dumps(data)}\n\n"


def _get_or_create_token(db: Session) -> GoogleCalendarToken:
    row = db.get(GoogleCalendarToken, 1)
    if row is None:
        row = GoogleCalendarToken(id=1, connected=False)
        db.add(row)
        db.commit()
        db.refresh(row)
    return row


def _decrypted_token(row: GoogleCalendarToken):
    """Return a SimpleNamespace with sensitive fields decrypted for in-memory use."""
    from types import SimpleNamespace
    return SimpleNamespace(
        id=row.id,
        access_token=decrypt_field(row.access_token),
        refresh_token=decrypt_field(row.refresh_token),
        token_uri=row.token_uri,
        client_id=row.client_id,
        client_secret=decrypt_field(row.client_secret),
        scopes=row.scopes,
        expires_at=row.expires_at,
        connected=row.connected,
    )


# ── Morning report SSE ────────────────────────────────────────────────────────

@router.get("/report")
async def get_report(
    db: Session = Depends(get_db),
    ollama: OllamaClient = Depends(get_ollama),
) -> StreamingResponse:
    """Stream the morning briefing as SSE tokens."""
    active_model = settings_crud.get_value(db, "active_model", "llama3.1:8b")
    profile = profile_crud.get_profile(db)
    token_row = _decrypted_token(_get_or_create_token(db))

    async def event_stream() -> AsyncIterator[str]:
        try:
            async for token in morning_report_service.generate(
                profile=profile,
                token_row=token_row,
                model=active_model,
                ollama=ollama,
            ):
                yield _sse({"type": "token", "content": token})
            yield _sse({"type": "done"})
        except Exception as exc:
            yield _sse({"type": "error", "message": str(exc)})

    return StreamingResponse(
        event_stream(),
        media_type="text/event-stream",
        headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no"},
    )


# ── Integration status ────────────────────────────────────────────────────────

@router.get("/report/status")
def report_status(db: Session = Depends(get_db)):
    """Return which integrations are ready."""
    token_row = _get_or_create_token(db)
    return {
        "weather": weather_client.available,
        "news": news_client.available,
        "web_search": bool(app_settings.ollama_api_key),
        "calendar": token_row.connected,
        "calendar_configured": calendar_client.configured,
    }


# ── Google Calendar OAuth ─────────────────────────────────────────────────────

@router.get("/report/calendar/auth")
def calendar_auth():
    """Return the Google OAuth consent URL."""
    try:
        url = calendar_client.get_auth_url()
        return {"auth_url": url}
    except Exception as exc:
        return {"error": str(exc)}


class CalendarCallbackRequest(BaseModel):
    code: str


@router.post("/report/calendar/callback")
def calendar_callback(
    body: CalendarCallbackRequest,
    db: Session = Depends(get_db),
):
    """Exchange auth code for tokens and persist them."""
    try:
        token_data = calendar_client.exchange_code(body.code)
    except Exception as exc:
        return {"success": False, "error": str(exc)}

    row = _get_or_create_token(db)
    # Encrypt sensitive OAuth fields before persisting
    row.access_token = encrypt_field(token_data["access_token"])
    row.refresh_token = encrypt_field(token_data.get("refresh_token"))
    row.token_uri = token_data.get("token_uri")
    row.client_id = token_data.get("client_id")
    row.client_secret = encrypt_field(token_data.get("client_secret"))
    row.scopes = token_data.get("scopes")
    row.connected = True
    db.commit()
    return {"success": True}


@router.delete("/report/calendar")
def calendar_disconnect(db: Session = Depends(get_db)):
    """Revoke Google Calendar connection."""
    row = _get_or_create_token(db)
    row.access_token = None
    row.refresh_token = None
    row.connected = False
    db.commit()
    return {"disconnected": True}


# ── Schedule settings ─────────────────────────────────────────────────────────

@router.get("/report/latest")
def report_latest(db: Session = Depends(get_db)):
    """Return the most recently cached scheduled report (may be empty)."""
    content = settings_crud.get_value(db, "last_report_content", "")
    generated_at = settings_crud.get_value(db, "last_report_generated_at", "")
    return {"content": content, "generated_at": generated_at}


class ScheduleUpdate(BaseModel):
    enabled: bool
    time: str  # "HH:MM" in 24-hour UTC


@router.get("/report/schedule")
def get_schedule(db: Session = Depends(get_db)):
    """Return current scheduling configuration."""
    return {
        "enabled": settings_crud.get_value(db, "report_schedule_enabled", "false") == "true",
        "time": settings_crud.get_value(db, "morning_report_time", "07:00"),
    }


@router.put("/report/schedule")
def update_schedule(body: ScheduleUpdate, db: Session = Depends(get_db)):
    """Update scheduling configuration and reschedule the background job."""
    settings_crud.update_many(db, {
        "report_schedule_enabled": "true" if body.enabled else "false",
        "morning_report_time": body.time,
    })
    # Reschedule the live APScheduler job
    try:
        from core.scheduler import report_scheduler
        report_scheduler.reschedule(enabled=body.enabled, time_str=body.time)
    except Exception as exc:
        # Scheduler may not be running in test environments
        import logging
        logging.getLogger(__name__).warning("Could not reschedule: %s", exc)
    return {"enabled": body.enabled, "time": body.time}


@router.get("/report/calendar/events")
def calendar_events(db: Session = Depends(get_db)):
    """Return today's calendar events."""
    raw = _get_or_create_token(db)
    if not raw.connected:
        return {"events": [], "connected": False}
    token_row = _decrypted_token(raw)
    events = calendar_client.get_today_events(token_row)
    return {"events": [e.to_dict() for e in events], "connected": True}
